feat: add `l10n` localization and set configuration  (#8)
* feat: integrate `Widget Book` with a sample button code #3
- add `ButtonIconState` enum
- add `customButtonWidgetUseCase` for `custom button` widget
- add `CustomButtonWidget`
- update `main` & add widget book required setup
- add `main.directories`
- comment `widget_test`

* feat: add `theme data` details to `pactus gui widget book` #3
- add/create `SurfacePallet`
- add/crete `OnSurfacePallet`
- add/create `AppThemeData`
- add/create `AppTheme`
- add `fluent_ui` package to `pubspec.yaml`
- add `ThemeAddon` to `WidgetBookApp` according to new themes
- update `main.dart` file
- add/create `InterTextStyles` according text styles that defined in Figma design
- update `CustomButtonWidget`
- add/create `AppScaffold` to show light & dark mode in output result

* update: migrate `AppThemeDate` & `AppTheme` from `material` to `FluentUI`
- update `AppThemeDate`
- update `AppTheme`

* test: add sample test to verify CI pipeline fix

* refactor(feature:main:language): changing translation package from `easy localization` to `l10n_flutter`

* ci: update pipeline to ensure localization tests succed

* style: clean up code style and restructure layout

* update: update `CHANGELOG.md` & `pubspec.yaml` files

* update: update `build_runner.sh` for generate files

* docs: add documentation for some files

---------

Co-authored-by: pouria.moradi <P@M14030619>
Co-authored-by: pouria.moradi <pooriya.mrd1378@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,7 +2,7 @@ name: Linting & Tests Validation
 on:
   pull_request:
     branches:
-      - develop
+      - main
 jobs:
   lint_and_test:
     runs-on: ubuntu-latest
@@ -15,47 +15,47 @@ jobs:
           flutter-version: '3.24.5'
       - name: Install dependencies
         run: flutter pub get
-      - name: Run Dart Format Check (Efficient)
+      - name: Generate Localization Files
+        id: gen_l10n
         run: |
-          dart format . --set-exit-if-changed --output none || (
+          # Run the command to generate localization files and capture the output
+          output=$(flutter gen-l10n)
+          echo "$output"
+          
+          # Check if there are untranslated messages in the output
+          if echo "$output" | grep -q "untranslated message"; then
+            echo "::error file=lib/l10n/l10n.yaml::Error: Untranslated messages detected in your localization files."
+            echo "::error::There are untranslated messages in the following languages:"
+            echo "$output" | grep "untranslated message"
+            echo "::error::Please ensure that all translations are provided in the respective .arb files."
+            exit 1
+          fi
+      - name: Check Localization Files
+        run: |
+          git diff --exit-code lib/l10n/ || (
+            echo "Localization files are outdated. Run 'flutter gen-l10n' and commit changes.";
+            exit 1;
+          )
+
+      # New step to check changes in source code
+      - name: Check if translations_utils.dart has changes
+        run: |
+          git diff --exit-code lib/src/core/utils/gen/localization/translations_utils.dart || (
+            echo "Error: Changes detected in translations_utils.dart. Please run the necessary custom translation utilities and commit changes.";
+            exit 1;
+          )
+
+      - name: Run Dart Format Check
+        run: |
+          dart format . --set-exit-if-changed || (
             echo "Code formatting issues detected. Run 'dart format .' and commit the changes.";
             exit 1;
           )
       - name: Run Flutter Analyze
         run: flutter analyze
-      - name: Generate Localization Files (Easy Localization)
-        run: |
-          # Generate locale keys
-          dart run easy_localization:generate -f keys -o locale_keys.g.dart --source-dir=assets/translations --output-dir=lib/src/core/utils/gen/localization || (
-            echo "Error: Failed to generate locale keys.";
-            exit 1;
-          )
-      - name: Run Dart Format and Check Localization Files Changes
-        run: |
-          # Run dart format without failing the step
-          dart format . || echo "dart format completed with warnings, but continuing pipeline."
-      
-          # Check if there are changes in the localization files after generation
-          git diff --exit-code lib/src/core/utils/gen/localization || (
-            echo "Error: Localization files are outdated. Run the generation command and commit the changes.";
-            exit 1;
-          )
-      - name: Generate Assets Files
-        run: |
-          # Command to rebuild asset files
-          dart run build_runner build --delete-conflicting-outputs --build-filter="lib/src/core/utils/gen/assets/*.dart" || (
-            echo "Error: Failed to generate asset files.";
-            exit 1;
-          )
-      - name: Check Asset Files Changes
-        run: |
-          # Check if there are changes after generating asset files
-          git diff --exit-code lib/src/core/utils/gen/assets || (
-            echo "Error: Asset files are outdated. Run the generation command and commit the changes.";
-            exit 1;
-          )
       - name: Run tests
         run: flutter test
+
   merge_check:
     runs-on: ubuntu-latest
     needs: lint_and_test
@@ -64,4 +64,4 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Merge Pull Request
-        run: echo "Linting and tests passed successfully.Merge request is ready for merge"
+        run: echo "Linting and tests passed successfully. Merge request is ready for merge"
